<a href="https://colab.research.google.com/github/Anish-S-tech/my-ml-journey/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy - Numerical Python

import numpy as np

array_1d = np.array([1,2,3,4,5])  # creates an ndarray (numpy array is called ndarray) [here 1D array]
print(array_1d)

[1 2 3 4 5]


In [ ]:
array_2d = np.array([[1,2,0],[3,4,5]]) # 2d array
print(array_2d)

[[1 2 0]
 [3 4 5]]


In [ ]:
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  # creating 3d array
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
all_zeros = np.zeros((3,2))  # creates a 3x2 array with all zero entries
all_ones = np.ones((2,4))  # creates a 2x4 array with all one as entries
all_range = np.arange(0,10,1) # creates an 1D array with given range (start,end,step)

print(all_zeros)
print()
print(all_ones)
print()
print(all_range)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("In 2d array:", arr2d[1,0])  # accessing elements in 2d array (accessing in 1d array is similar to lists)

array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("In 3d array:" , array_3d[0,1,0]) # accessing elements in 3d array


In 2d array: 4
In 3d array: 3


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Slicing in 2d array: ", arr2d[:,0]) # first element in all columns (2d slicing)

arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("Slicing in 3d array: ", arr3d[0,:,1]) # 3d slicing

Slicing in 2d array:  [1 4 7]
Slicing in 3d array:  [2 4]


In [ ]:
first2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second2d = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(first2d+second2d)
print()
print(first2d-second2d)
print()
print(first2d*second2d)
print()
print(first2d/second2d)
print()

[[11 13 15]
 [17 19 21]
 [23 25 27]]

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]



In [ ]:
# broadcasting rules

# two arrays having same shape - always works
# not same shape, but compatible - numpy stretches the array and performs operations (eg. shapes with (2,3) and (2,1))
# incompatible shapes - throws an error

In [ ]:
# arithmetic operations (using functions)

first2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second2d = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

added = np.add(first2d,second2d)
subtracted = np.subtract(first2d,second2d)
multiplied = np.multiply(first2d,second2d)
divided = np.divide(first2d,second2d)

print(added)
print()
print(subtracted)
print()
print(multiplied)
print()
print(divided)
print()

[[11 13 15]
 [17 19 21]
 [23 25 27]]

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]



In [ ]:
# unary operations (without need of multiple arrays)

first2d = np.array([[-1, 2, -3], [4, -5, 6], [7, 8, -9]])

abs_values = np.absolute(first2d) # absolute values
sine_values = np.sin(abs_values) # sine values of each element
sqrt_values = np.sqrt(abs_values) # sqrt of each element

print(abs_values)
print()
print(sine_values)
print()
print(sqrt_values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
# unary operations available in numpy

# Operation Type	      NumPy Function	                        Description
# Absolute value	      np.abs(x)	                              Converts negative values to positive
# Square root	          np.sqrt(x)	                            √ each element
# Exponential	          np.exp(x)	                              e^x for each element
# Natural log	          np.log(x)	                              ln(x)
# Trigonometric	        np.sin(x), np.cos(x), np.tan(x)	        Element-wise sin/cos/tan
# Sign	                np.sign(x)	                            Returns -1, 0, 1 depending on value of x
# Negative	            -x	                                    Negates each element
# Reciprocal	          np.reciprocal(x)	                      1 / x
# Rounding	            np.round(x)	                            Round each element
# Conjugate (complex)	  np.conjugate(x)	                        Complex conjugate

In [ ]:
dtypes = [('Names','S10'),('grad_year',int),('cgpa',float)] # creating a structured data type (datatypes of each values)

values = [('Alice',2016,8.9),('Charlie',2019,8.0),('Bob',2015,8.4),('Eve',2025,9.0)]

arr = np.array(values, dtype = dtypes)

print('Array unsorted:')
print()
print(arr)
print()

print("Array sorted by names:")
print()
print(np.sort(arr, order = 'Names'))
print()

print('Array sorted by grad_year and cgpa:')
print()
print(np.sort(arr,order = ['grad_year','cgpa']))

Array unsorted:

[(b'Alice', 2016, 8.9) (b'Charlie', 2019, 8. ) (b'Bob', 2015, 8.4)
 (b'Eve', 2025, 9. )]

Array sorted by names:

[(b'Alice', 2016, 8.9) (b'Bob', 2015, 8.4) (b'Charlie', 2019, 8. )
 (b'Eve', 2025, 9. )]

Array sorted by grad_year and cgpa:

[(b'Bob', 2015, 8.4) (b'Alice', 2016, 8.9) (b'Charlie', 2019, 8. )
 (b'Eve', 2025, 9. )]


In [ ]:
first2d = np.array([[-1, 2, -3], [4, -5, 6], [7, 8, -9]])

print("Array datatype: ", type(first2d))  # type of array object
print("Array dimension: ", first2d.ndim)  # dimension of array (axes)
print("Array shape: ", first2d.shape)  # shape of array
print("Array size: ", first2d.size)  # size of array (total number of elements)
print("Array stores each element as type: ", first2d.dtype)  # type of elements in array

Array datatype:  <class 'numpy.ndarray'>
Array dimension:  2
Array shape:  (3, 3)
Array size:  9
Array stores each element as type:  int64


In [ ]:
# types of axes of array

# axis = 0 (1d array)
# axis = 1 (2d array)
# axis = 2 (3d array)

In [ ]:
# creating array using np.fromiter function

list1 = [2,4,9,1,5]

fromiter_array = np.fromiter(list1,dtype=int)  # creates an array from iterable [dtype = '' is mandatory in fromiter]

print(fromiter_array)

[2 4 9 1 5]


In [ ]:
linspace_arr = np.linspace(4,10,3,dtype=int) # creates an np array within 4 to 10 of size 3 (start,end,no.of elements)
print(linspace_arr)

[ 4  7 10]


In [ ]:
print(np.empty([2,2],dtype=int,order='C'))  # creating an empty array with random garbage values

[[4620918397663497421 4621199872640208077]
 [4620693217682128896 4621256167635550208]]


In [ ]:
# order parameter in ndarrays

# order = 'C' (C - style) : Row by row storage in memory.

# order = 'F' (Fortran order ): Column by column storage.

In [ ]:
full_array = np.full((2,3),5)  # creates a 2x3 array filled with value 5 [np.full(dim,val)]

print(full_array)

[[5 5 5]
 [5 5 5]]


In [ ]:
rand_array = np.random.rand(2,3)  # creates a 2x3 array filled with random values between 0 and 1 [uniformly distributed values (like values in probability)]
randn_array = np.random.randn(2,4) # creates a 2x4 array random values (standard normal distribution) [mean = 0 , std_dev = 1]
randint_array = np.random.randint(2,5,size=(2,2)) # creates a random 2x2 array between values 2,5  (start,stop,size)

print(rand_array)
print()
print(randn_array)
print()
print(randint_array)

[[0.41208401 0.71155057 0.48512839]
 [0.93890885 0.98768248 0.42833153]]

[[1.96419128 0.56233596 0.20964306 0.16936885]
 [1.37547294 0.88756544 0.51077783 0.80011249]]

[[2 3]
 [3 4]]


In [ ]:
# uniform distribution = all values lie between 0 to 1

# standard normal distribution = most of the values are around 0 (because this distribution forms a bell curve with 0 as centre)

In [ ]:
identity = np.eye(3)   # creates an identity matrix of nxn (here 3x3)
diagonal = np.diag([2,4,1,2]) # creates an identity matrix with diagonals as the elements in list and size as len(list) x len(list)
like_zero = np.zeros_like(diagonal)  # creates a array with zeros with dimension as same as the array given as parameter (here array diagonal)
like_one = np.ones_like(identity)  # creates a array with ones with dimension as same as the array given as parameter (here array identity)

print(identity)
print()
print(diagonal)
print()
print(like_zero)
print()
print(like_one)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[2 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 2]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [ ]:
# boolean indexing

arr = np.array([10, 15, 20, 25, 30])

print(arr [ arr>20 ])  # prints only the values which satisfies the condition

print( arr[ (arr>=10) & (arr<=20) ]) # using AND operator in boolean indexing

[25 30]
[10 15 20]


In [ ]:
# fancy indexing

arr = np.array([10,20,30,40,50])

indices = [0,2,4]

print(arr[indices]) # prints arr[0], arr[2] and arr[4] together in one statement

[10 30 50]


In [ ]:
# integer array indexing

arr = np.array([10,20,30,40,50])

print(arr[[0,2,4]])

[10 30 50]


In [ ]:
# indexing using ellipsis (...)

first2d = np.array([[-1, 2, -3], [4, -5, 6], [7, 8, -9]])

print(first2d[...,0 ])  # prints first elements in all rows (independent of dimension)

[-1  4  7]


In [ ]:
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(array_3d[..., 0])  # ellipsis in 3d array

[[1 3]
 [5 7]]


In [ ]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print()

print(array[:,:,np.newaxis])  # np.newaxis is used to increase the dimensions of an existing NumPy array by 1, turning a 1D array into a row or column vector. (Used in ML)

[[1 2 3]
 [4 5 6]]

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
array = np.array([[1,2,3],[4,5,6]])

array[1,:] = 10  # modifying multiple values in a single statement

print(array)

[[ 1  2  3]
 [10 10 10]]


In [ ]:
arr = np.array([[10, 20, 30], [40, 5, 66], [70, 88, 94]])

print(arr)
print()
print(arr[[0,-1]])  # prints first and last rows (we can also slice like this)

[[10 20 30]
 [40  5 66]
 [70 88 94]]

[[10 20 30]
 [70 88 94]]


In [ ]:
n_arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]],
                  [[50, 65, 8], [70, 85, 10], [11, 22, 33]],
                 [[19, 69, 36], [1, 5, 24], [4, 20, 96]]])

print(n_arr)
print()
print()
print(n_arr[:,[0,1]]) # prints first 2 rows in every 2d matrix

[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]

 [[19 69 36]
  [ 1  5 24]
  [ 4 20 96]]]


[[[10 25 70]
  [30 45 55]]

 [[50 65  8]
  [70 85 10]]

 [[19 69 36]
  [ 1  5 24]]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
n = arr.size
N = 4             # 4 elements per row
M = n//N
arr1=arr.reshape(N,M)  # np.reshape(arr,(N,M)) does the same
display(arr1)
arr2=arr.reshape(2,8)  # reshaping 1d array to 2d array
print()
display(arr2)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [ ]:
np.reshape(arr,(2,1,8))  # reshaping 1d array into 3d array


array([[[ 1,  2,  3,  4,  5,  6,  7,  8]],

       [[ 9, 10, 11, 12, 13, 14, 15, 16]]])

In [ ]:
array = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

np.reshape(array, (9))  # N-d array to 1-d array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

arr1 = np.reshape(array, (2,2,-1))  # converting 1d to 3d though we don't know dimensions
display(arr1)
print()

arr2 = np.reshape(array, (4,-1))  # converting 1d to 2d though we don't know dimensions
display(arr2)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(3,5)  # resize() - fills with 0 if the array can't be reshaped to the given dimension mathematically whereas reshape() throws an error
display(arr)

array([[1, 2, 3, 4, 5],
       [6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
a = np.array([1,2,3])  # stacking 1d array (using np.stack())
b = np.array([4,5,6])

np.stack((a,b),axis=0)  # row-wise stacking


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a,b),axis=1)  # col-wise stacking

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x=np.array([[1,2,3],
            [4,5,6]])

y=np.array([[7,8,9],
            [10,11,12]])

np.stack((x,y),axis = 0)  # Just stacking

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
np.stack((x,y),axis=1)  # row wise stacking  (We can do stacking for more than two arrays also)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [ ]:
np.stack((x,y),axis=2)  # col-wise stacking

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [ ]:
m=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],

            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

n=np.array([[[51,52,53],
            [54,55,56],
            [57,58,59]],

            [[110,111,112],
            [113,114,115],
            [116,117,118]]])

In [ ]:
np.stack((m,n),axis=0) # Just stacking

array([[[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 10,  11,  12],
         [ 13,  14,  15],
         [ 16,  17,  18]]],


       [[[ 51,  52,  53],
         [ 54,  55,  56],
         [ 57,  58,  59]],

        [[110, 111, 112],
         [113, 114, 115],
         [116, 117, 118]]]])

In [ ]:
np.stack((m,n),axis = 1)  # 2d array wise

array([[[[  1,   2,   3],
         [  4,   5,   6],
         [  7,   8,   9]],

        [[ 51,  52,  53],
         [ 54,  55,  56],
         [ 57,  58,  59]]],


       [[[ 10,  11,  12],
         [ 13,  14,  15],
         [ 16,  17,  18]],

        [[110, 111, 112],
         [113, 114, 115],
         [116, 117, 118]]]])

In [ ]:
np.stack((m,n),axis = 2)  # 2d row wise stack

array([[[[  1,   2,   3],
         [ 51,  52,  53]],

        [[  4,   5,   6],
         [ 54,  55,  56]],

        [[  7,   8,   9],
         [ 57,  58,  59]]],


       [[[ 10,  11,  12],
         [110, 111, 112]],

        [[ 13,  14,  15],
         [113, 114, 115]],

        [[ 16,  17,  18],
         [116, 117, 118]]]])

In [ ]:
np.stack((m,n),axis = 3)  # 2d column wise stack

array([[[[  1,  51],
         [  2,  52],
         [  3,  53]],

        [[  4,  54],
         [  5,  55],
         [  6,  56]],

        [[  7,  57],
         [  8,  58],
         [  9,  59]]],


       [[[ 10, 110],
         [ 11, 111],
         [ 12, 112]],

        [[ 13, 113],
         [ 14, 114],
         [ 15, 115]],

        [[ 16, 116],
         [ 17, 117],
         [ 18, 118]]]])

In [ ]:
arr = np.arange(0,6,1)
print(arr)
print()

np.split(arr,3)  # equal splitting

[0 1 2 3 4 5]



[array([0, 1]), array([2, 3]), array([4, 5])]

In [ ]:
np.array_split(arr,4)  # unequal splitting

[array([0, 1]), array([2, 3]), array([4]), array([5])]

In [ ]:
array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])

np.split(array,3,axis=0)  # row wise splitting

[array([[3, 2, 1]]), array([[8, 9, 7]]), array([[4, 6, 5]])]

In [ ]:
np.split(array,3,axis=1)  # col-wise splitting

[array([[3],
        [8],
        [4]]),
 array([[2],
        [9],
        [6]]),
 array([[1],
        [7],
        [5]])]

In [ ]:
np.vsplit(array, 3)  # Vertical splitting (same as np.split(array,3,axis=1))

[array([[3, 2, 1]]), array([[8, 9, 7]]), array([[4, 6, 5]])]

In [ ]:
np.hsplit(array,3)  # horizontal splitting (same as np.split(array,3,axis=0))

[array([[3],
        [8],
        [4]]),
 array([[2],
        [9],
        [6]]),
 array([[1],
        [7],
        [5]])]

In [ ]:
original_3d_array = np.arange(24).reshape((2, 3, 4))
print(original_3d_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
np.dsplit(original_3d_array, 2)  # splitting using depth

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [ ]:
# Broadcasting in numpy

# Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

n = 10

array_2d = array_2d + n
print(array_2d)

[[11 12 13]
 [14 15 16]]


In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([[4,5,6],[7,8,9]])

print(a1 + a2)  # automatically expands 1d array to 2d array

[[ 5  7  9]
 [ 8 10 12]]


In [ ]:
ages = np.array([18,17,19,29,25,31,27])

age_group = np.array(['Minor','Adult'])

result = np.where(ages > 18, age_group[1], age_group[0])  # broadcasting in conditional operators

print(result)

['Minor' 'Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


In [ ]:
# broadcasting rules

# two arrays having same shape - always works
# not same shape, but compatible - numpy stretches the array and performs operations (eg. shapes with (2,3) and (2,1))
# incompatible shapes - throws an error

In [ ]:
# arithmetic operations on numpy arrays (+,-,*,/,%,^)

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

addition = np.add(a,b)
subtraction = np.subtract(a,b)
multiplication = np.multiply(a,b)
division = np.divide(a,b)
exponential = np.power(a,b)
modulus = np.mod(a,b)

print(addition)
print()
print(subtraction)
print()
print(multiplication)
print()
print(division)
print()
print(exponential)
print()
print(modulus)

[  7  77  23 130]

[ 3 67  3 70]

[  10  360  130 3000]

[ 2.5        14.4         1.3         3.33333333]

[                 25          1934917632        137858491849
 1152921504606846976]

[ 1  2  3 10]


In [ ]:
arr = [[14, 17, 12, 33, 44],
	[15, 6, 27, 8, 19],
	[23, 2, 54, 1, 4,]]

sum = np.sum(arr)  # just calculates sum of elements in 2d array

integer_sum = np.sum(arr,dtype=np.int64)  # calculates sum of elements in 2d array (integer datatype)

float_sum = np.sum(arr,dtype=np.float64)  # calculates sum of elements in 2d array (float datatype)

axis_0 = np.sum(arr,axis=0)  # column wise addition
axis_1 = np.sum(arr,axis=1)  # row wise addition
keep_dims = np.sum(arr,axis=1,keepdims=True)  # maintains the dimension of original array

print(sum)
print(integer_sum)
print(float_sum)
print(axis_0)
print(axis_1)
print(keep_dims)

279
279
279.0
[52 25 93 42 67]
[120  75  84]
[[120]
 [ 75]
 [ 84]]


In [ ]:
# mean function for array [can use all the methods we used for sum() function]

arr = [[14, 17, 12, 33, 44],
       [15, 6, 27, 8, 19],
       [23, 2, 54, 1, 4, ]]

mean = np.mean(arr)
mean_row = np.mean(arr,axis=1)
mean_col = np.mean(arr,axis=0)
keep_dims = np.mean(arr,axis=1,keepdims=True)

print(mean)
print(mean_row)
print(mean_col)
print(keep_dims)

18.6
[24.  15.  16.8]
[17.33333333  8.33333333 31.         14.         22.33333333]
[[24. ]
 [15. ]
 [16.8]]


In [ ]:
arr1 = np.array([2, 8, 125])
arr2 = np.array([3, 3, 15])

print(np.maximum(arr1,arr2))  # maximum by comparing 2 or more arrays and preserves the dimension
                              # Note: NaN is greater than 0

[  3   8 125]


In [ ]:
arr1 = np.array([2, 8, 125])
arr2 = np.array([3, 3, 15])

print(np.minimum(arr1,arr2))  # minimum by comparing 2 or more arrays and preserves the dimension

[ 2  3 15]


In [ ]:
# Universal functions (ufuncs in short)

# used for faster element wise operations

#           Basic ufuncs in trigonometry

# Function	                    Description

# sin, cos, tan       	        compute the sine, cosine, and tangent of angles
# arcsin, arccos, arctan      	calculate inverse sine, cosine, and tangent
# hypot	                        calculate the hypotenuse of the given right triangle
# sinh, cosh, tanh	            compute hyperbolic sine, cosine, and tangent
# arcsinh, arccosh, arctanh	    compute inverse hyperbolic sine, cosine, and tangent
# deg2rad	                      convert degree into radians
# rad2deg	                      convert radians into degree

In [ ]:
angles = np.array([0, 30, 45, 60, 90, 180])

radians = np.deg2rad(angles)

sine_val = np.sin(radians)
cosine_val = np.cos(radians)
tangent_val = np.tan(radians)

arcsin_val = np.arcsin(radians)
arccos_val = np.arccos(radians)
arctan_val = np.arctan(radians)

sinh_val = np.sinh(radians)
cosh_val = np.cosh(radians)
tanh_val = np.tanh(radians)

arcsinh_val = np.arcsinh(radians)
arccosh_val = np.arccosh(radians)
arctanh_val = np.arctanh(radians)

print(sine_val)
print()
print(cosine_val)
print()
print(tangent_val)
print()
print(arcsin_val)
print()
print(arccos_val)
print()
print(arctan_val)
print()
print(sinh_val)
print()
print(cosh_val)
print()
print(tanh_val)
print()
print(arcsinh_val)
print()
print(arccosh_val)
print()
print(arctanh_val)




[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]

[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00]

[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.22464680e-16]

[0.         0.55106958 0.90333911        nan        nan        nan]

[1.57079633 1.01972674 0.66745722        nan        nan        nan]

[0.         0.48234791 0.66577375 0.80844879 1.00388482 1.26262726]

[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]

[ 1.          1.14023832  1.32460909  1.60028686  2.50917848 11.59195328]

[0.         0.48047278 0.6557942  0.78071444 0.91715234 0.99627208]

[0.         0.50221899 0.72122549 0.91435666 1.23340312 1.86229574]

[       nan        nan        nan 0.30604211 1.02322748 1.81152627]

[0.         0.58128501 1.05930617        nan        nan        nan]


/tmp/ipython-input-2733857309.py:9: RuntimeWarning: invalid value encountered in arcsin
  arcsin_val = np.arcsin(radians)
/tmp/ipython-input-2733857309.py:10: RuntimeWarning: invalid value encountered in arccos
  arccos_val = np.arccos(radians)
/tmp/ipython-input-2733857309.py:18: RuntimeWarning: invalid value encountered in arccosh
  arccosh_val = np.arccosh(radians)
/tmp/ipython-input-2733857309.py:19: RuntimeWarning: invalid value encountered in arctanh
  arctanh_val = np.arctanh(radians)


In [ ]:
#        ufunc's Statistical Functions in NumPy

# Function	                    Description
# amin, amax	                  returns minimum or maximum of an array or along an axis
# ptp	                          returns range of values (maximum-minimum) of an array or along an axis
# percentile(a, p, axis)      	calculate the pth percentile of the array or along a specified axis
# median	                      compute the median of data along a specified axis
# mean	                        compute the mean of data along a specified axis
# std	                          compute the standard deviation of data along a specified axis
# var	                          compute the variance of data along a specified axis
# average	                      compute the average of data along a specified axis

In [ ]:
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

print(np.amin(weight))
print()
print(np.amax(weight))
print()
print(np.ptp(weight))
print()
print(np.percentile(weight,70))
print()
print(np.mean(weight))
print()
print(np.median(weight))
print()
print(np.std(weight))
print()
print(np.var(weight))
print()
print(np.average(weight))
print()

45.0

73.25

28.25

55.317

54.3225

51.6

8.052773978574091

64.84716875

54.3225



In [ ]:
#        ufunc's Bit-twiddling functions in NumPy

# Function                        Description
# bitwise_and	                    performs bitwise and operation on two array elements
# bitwies_or	                    performs bitwise or operation on two array elements
# bitwise_xor	                    performs bitwise xor operation on two array elements
# invert	                        performs bitwise inversion of an array of elements
# left_shift	                    shift the bits of elements to the left
# right_shift	                     shift the bits of elements to the left

In [ ]:
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])

print(np.bitwise_and(even,odd))
print()
print(np.bitwise_or(even,odd))
print()
print(np.bitwise_xor(even,odd))
print()
print(np.invert(even))
print()
print(np.left_shift(even,1))
print()
print(np.right_shift(even,1))


[ 0  2  4  6  8 16 32]

[ 1  3  5  7  9 17 33]

[1 1 1 1 1 1 1]

[ -1  -3  -5  -7  -9 -17 -33]

[ 0  4  8 12 16 32 64]

[ 0  1  2  3  4  8 16]


In [ ]:
# Matrix manipulation (functions)

# add()
# subtract()
# multiply()  - element wise multiplication (not matrix multiplication)
# dot() [or] matmul()      - matrix multiplication
# divide()
# sqrt()
# sum(x,axis)
# T           - Transpose of matrix

In [ ]:
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print(np.dot(x,y))  # matrix multiplication
print()
print(np.sqrt(x))   # square root
print()
print(x.T)          # Transpose of matrix


[[25 28]
 [73 82]]

[[1.         1.41421356]
 [2.         2.23606798]]

[[1 4]
 [2 5]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print(np.inner(x,y))  # calculates inner product of arrays

# [x1.y1  x1.y2
#  x2.y1  x2.y2]

[[17 52]
 [13 62]]


In [ ]:
x = np.array([[3, 6, 4], [9, 4, 6]])
y = np.array([[1, 15, 7], [3, 10, 8]])

print(np.outer(x,y))  # calculates outer product of arrays

#  [x1.y1  x1.y2  x1.y3
#  x2.y1  x2.y2  x2.y3]

[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


In [ ]:
# cross product

x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])

print(np.cross(x,y))

[[ -9  51 -32]
 [-15   3   3]]


In [ ]:
# [   a₂*b₃ - a₃*b₂,
#     a₃*b₁ - a₁*b₃,
#     a₁*b₂ - a₂*b₁ ]     = C1 (let)

# first for A1 x B1  (A1 = [2,6,9], B1 = [7,5,6])
# a1 = 2, a2 = 6 a3 = 9
# b1 = 7, b2 = 5, b3 = 6

# then for A2 x B2  (A2 = [2,7,3], B2 = [3,12,3])
# a1 = 2, a2 = 7 a3 = 3
# b1 = 3, b2 = 12, b3 = 3

# Then, give it as like [[C1],[C2]]

In [ ]:
# determinant of matrix  (using numpy.linalg.slogdet())

A = np.array([[50, 29], [30, 44]])

sign, logdet = np.linalg.slogdet(A)  # returns sign, log value of determinant
res = sign * np.exp(logdet)

res2 = np.linalg.det(A)

print("Using numpy.linalg.slogdet: ",res)
print("Using numpy.linalg.det: ",res2)

Using numpy.linalg.slogdet:  1330.0000000000002
Using numpy.linalg.det:  1330.0000000000002


In [ ]:
# determinant using scipy

import scipy.linalg

P,L,U = scipy.linalg.lu(A)  # calculates by LU decomposition method (P - Permutation matrix, L- Lower triangular matrix, U - Upper triangular matrix)
res3 = np.prod(np.diag(U))  # product of diagonals of upper triangular elements = determinant of matrix
print(res3)

1330.0


In [ ]:
# finding inverse of a matrix (using np.linalg.inv())

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
# np.dot(a, b) performs standard matrix multiplication for 2D arrays.
# It multiplies rows of 'a' with columns of 'b' using dot product logic.
#
# Example:
# a = [[a₁, a₂],       → shape (2×2)
#      [a₃, a₄]]
#
# b = [[b₁, b₂],       → shape (2×2)
#      [b₃, b₄]]
#
# Result[i][j] = a[i][0]*b[0][j] + a[i][1]*b[1][j]
# Output shape is (a_rows, b_columns)
# This is the same as using the '@' operator or np.matmul(a, b)

In [ ]:
# dot product of two vectors

vec_a = 2 + 3j
vec_b = 4 + 5j

print(np.dot(vec_a,vec_b))


(-7+22j)


In [ ]:
# np.inner(a, b) computes the inner product between two arrays.
# For 2D arrays, it treats each row as a separate vector.
# It calculates the dot product of every row in 'a' with every row in 'b'.
#
# Example:
# a = [[a₁, a₂],       → row 0
#      [a₃, a₄]]       → row 1
#
# b = [[b₁, b₂],       → row 0
#      [b₃, b₄]]       → row 1
#
# Result[i][j] = dot(a[i], b[j]) = a[i][0]*b[j][0] + a[i][1]*b[j][1]
# Output is a matrix of shape (a_rows, b_rows) containing all pairwise dot products.

In [ ]:
# for 2d arrays various behaviours of products (here inner product)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.inner(a,b))

# Output logic

# [(1*5)+(2*6)     (1*7)+(2*8)
#  (5*3)+(6*4)     (3*7)+(8*4)]

[[17 23]
 [39 53]]


In [ ]:
# np.outer(a, b) computes the outer product between two arrays.
# It first flattens both 'a' and 'b' into 1D vectors.
# Then it creates a matrix where each element is a[i] * b[j].
#
# Example:
# a = [[a₁, a₂],       → flattened to [a₁, a₂, a₃, a₄]
#      [a₃, a₄]]
#
# b = [[b₁, b₂],       → flattened to [b₁, b₂, b₃, b₄]
#      [b₃, b₄]]
#
# Result[i][j] = a_flat[i] * b_flat[j]
# Output is a matrix of shape (a.size, b.size) containing all pairwise products.

In [ ]:
# Outer product

a = np.array([[1, 2], [3, 4]])  # Flattened to [1, 2, 3, 4]
b = np.array([[5, 6], [7, 8]])  # Flattened to [5, 6, 7, 8]
np.outer(a, b)
# Output: 4×4 matrix of all pairwise products


array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [ ]:
# cross product of 2 vectors

# 'a' and 'b' are 2D arrays where each row represents a 3D vector.
# For example:
# a = [[a₁, a₂, a₃],     → first 3D vector
#      [a₄, a₅, a₆]]     → second 3D vector
#
# b = [[b₁, b₂, b₃],     → first 3D vector
#      [b₄, b₅, b₆]]     → second 3D vector
#
# np.cross(a, b) computes the cross product row-wise:
#   For each pair of rows a[i] and b[i], it calculates:
#     x = a[i][1] * b[i][2] - a[i][2] * b[i][1]
#     y = a[i][2] * b[i][0] - a[i][0] * b[i][2]
#     z = a[i][0] * b[i][1] - a[i][1] * b[i][0]
#
# The result is a new array where each row is a vector perpendicular
# to both a[i] and b[i], following the right-hand rule.

In [ ]:

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(np.cross(a, b))


[[-6 12 -6]
 [-6 12 -6]]


In [ ]:
# np.vdot(a, b) computes the vector dot product between 'a' and 'b'.
# It first flattens both arrays into 1D vectors, regardless of their original shape.
# Then it multiplies corresponding elements and sums them up.
# If the elements are complex numbers, it takes the complex conjugate of 'a' before multiplying.
#
# Example:
# a = [[a₁, a₂, a₃],
#      [a₄, a₅, a₆]]   → flattened to [a₁, a₂, a₃, a₄, a₅, a₆]
#
# b = [[b₁, b₂, b₃],
#      [b₄, b₅, b₆]]   → flattened to [b₁, b₂, b₃, b₄, b₅, b₆]
#
# Result = conj(a₁)*b₁ + conj(a₂)*b₂ + ... + conj(a₆)*b₆
# Output is a single scalar value.
#
# Use np.vdot when working with complex-valued vectors or when you want a strict inner product
# that ignores shape and always returns a scalar.

In [ ]:
vec_a = np.array([[1, 4], [5, 6]])
vec_b = np.array([[2, 4], [5, 2]])

print(np.vdot(vec_a,vec_b))

55


In [ ]:
# Eigenvalues and Eigenvectors:
# ------------------------------
# Given a square matrix A, we want to find scalars (eigenvalues λ) and vectors (eigenvectors v)
# such that: A @ v = λ * v
#
# This equation means: when matrix A acts on vector v, the result is just a scaled version of v.
# The direction of v doesn't change—only its magnitude (scaled by λ).
#
# Step-by-step logic:
# 1. Compute the eigenvalues:
#    - Solve the characteristic equation: det(A - λ * I) = 0
#    - This gives all λ values where the matrix becomes singular (non-invertible)
#
# 2. Compute the eigenvectors:
#    - For each eigenvalue λ, solve: (A - λ * I) @ v = 0
#    - This gives the vector v that satisfies the transformation rule
#
# Geometric intuition:
# - Eigenvectors point in directions that remain unchanged under the transformation A
# - Eigenvalues tell you how much those vectors are stretched, compressed, or flipped
#
# Example:
# A = [[2, 1],
#      [1, 3]]
# eigenvalues, eigenvectors = np.linalg.eig(A)
#
# Output:
# - 'eigenvalues' is a 1D array of λ values
# - 'eigenvectors' is a 2D array where each column corresponds to an eigenvector of A
#
# Use cases:
# - Principal Component Analysis (PCA): directions of maximum variance
# - Stability analysis: system growth or decay
# - Diagonalization: simplifying matrix powers
# - Quantum mechanics: observable quantities and state evolution

In [ ]:
A = np.array([[2, 1],
              [1, 3]])

eigen_values, eigen_vectors = np.linalg.eig(A)

print(eigen_values)
print()
print(eigen_vectors)

[1.38196601 3.61803399]

[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [ ]:
import numpy as np

arr = np.random.randint(low=0,high=5,size=10)  # generates random numbered 1d array from 0 to 4 with size 10
print(arr)

[2 0 1 4 2 2 1 4 0 0]


In [ ]:
arr = np.random.randint(low=5,high=10,size=(2,4))  # random array of size 2x4
print(arr)

[[6 7 5 9]
 [5 8 9 8]]


In [ ]:
arr = np.random.randint(2,7,(2,3,4))  # random array with low = 2, high = 7 and size = 2x3x4
print(arr)

[[[4 2 2 3]
  [6 3 3 3]
  [2 5 4 5]]

 [[4 3 6 5]
  [5 5 4 5]
  [6 6 6 2]]]


In [ ]:
# normal distribution

# numpy.random.normal(loc=0.0, scale=1.0, size=None)

# loc = specifies the centre of the distribution
# scale = specifies the spread (standard deviation) of the distribution
# size = size of the returned array

random_number = np.random.normal()  # generates single random number (normal distribution)
print(random_number)

-0.821161976215166


In [ ]:
random_normal_array = np.random.normal(size=7)  # generates array of random number obeys normal distribution
print(random_normal_array)

# we can visualize it through matplotlib

[ 0.23052487 -1.06741149 -0.74929066  1.50567439  0.84139883  0.72943618
 -1.4319252 ]


In [ ]:
# binomial distribution

# numpy.random.binomial(n,p,size=None)

# n = number of trials (eg. Number of coin flips)
# p = probability of success on each trial (eg. probability of getting heads on that flip)
# size = shape of returned array

binomial = np.random.binomial(n=10,p=0.5)  # single element
print(binomial)

1


In [ ]:
binomial_array = np.random.binomial(n=10,p=0.5,size=6)  # generates array of random numbers obeys binomial distribution
print(binomial_array)

# we can visualize it through matplotlib

[6 5 4 6 3 3]


In [ ]:
# poisson distribution

# np.random.poisson(lam = 1.0, size = None)

# lam = average number of events (lambda) expected to occur in the interval
# size = shape of array to return

poisson = np.random.poisson(lam = 5)  # generates single element
print(poisson)

7


In [ ]:
poisson_arr = np.random.poisson(lam=5,size=5) # generates array of random numbers obeys poisson distribution (visualize it through matplotlib)
print(poisson_arr)

[4 6 4 0 3]


In [ ]:
# Uniform distribution

# numpy.random.uniform(low=0,high=1,size=None)

# low = lower bound of range (default = 0)
# high = higher bound of range (default = 1)
# size = shape of the array to be returned

uniform = np.random.uniform()  # generates single element
print(uniform)

0.6262318815404152


In [ ]:
uniform_array = np.random.uniform(low=0,high=1,size=5)  # generates array of random numbers obeys uniform distribution (visualize it through matplotlib)
print(uniform_array)

[0.26251171 0.49755313 0.28180479 0.11189324 0.01720318]


In [ ]:
# exponential distribution

# numpy.random.exponential(scale = 1.0,size=None)

# scale = inverse of rate parameter (beta = 1/lambda) which determines spread of distribution
# size = shape of array

exponential = np.random.exponential()  # generates single element
print(exponential)

1.6719453634205532


In [ ]:
exponential_array = np.random.exponential(scale=3,size=6) # generates array of random numbers obeys exponential distribution (visualize it through matplotlib)
print(exponential_array)

[2.03390513 5.91429973 4.05490367 1.25671199 0.23500705 5.18341391]


In [ ]:
# Chi square distribution

# numpy.random.chisquare(df,size=None)

# df = Degrees of freedom (k) which affects the shape of distribution
# size = shape of the distribution

chisquare = np.random.chisquare(df=2)  # generates single element
print(chisquare)

1.855926374497335


In [ ]:
chisquare_arr = np.random.chisquare(df=2,size=(2,3)) # generates array of random numbers obeys chisquare distribution (visualize it through matplotlib)
print(chisquare_arr)

[[2.1360706  1.75861208 0.51155014]
 [1.37641255 1.63352873 7.53395606]]


In [ ]:
# Sparse matrix - If most of the elements of the matrix has 0 as value, then it's called sparse matrix

# creating sparse matrix using scipy

# Format                           Best For                                 Description

# csr_matrix                       Fast row slicing, math operations        Compressed Sparse Row good for arithmetic and row access.

# csc_matrix                       Fast column slicing                      Compressed Sparse Column efficient for column-based ops.

# coo_matrix                       Easy matrix building                     Coordinate format using (row, col, value) triples.

# lil_matrix                       Incremental row-wise construction        List of Lists, modify rows easily before converting.

# dia_matrix                       Diagonal-dominant matrices               Stores only diagonals, saves space.

# dok_matrix                       Fast item assignment                     Dictionary-like, ideal for random updates.

In [ ]:
# implementing csr matrix (compressed sparse row matrix) [stores data row wise]

import numpy as np
from scipy.sparse import csr_matrix

data = np.array([2,4,7,3,9])
row = np.array([0,0,2,3,1])
col = np.array([1,3,2,3,0])

mat = csr_matrix((data,(row,col)),shape=(4,5))
print(mat)  # coordinates form
print()

mat_arr = mat.toarray()
print(mat_arr)  # matrix form

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (4, 5)>
  Coords	Values
  (0, 1)	2
  (0, 3)	4
  (1, 0)	9
  (2, 2)	7
  (3, 3)	3

[[0 2 0 4 0]
 [9 0 0 0 0]
 [0 0 7 0 0]
 [0 0 0 3 0]]


In [ ]:
# implementing csc_matrix (compressed sparse column) [stores data column wise]

import numpy as np
from scipy.sparse import csc_matrix

data = np.array([2,4,7,3,9])
row = np.array([0,0,2,3,1])
col = np.array([1,3,2,3,0])

mat = csc_matrix((data,(row,col)),shape=(4,5))
print(mat)  # coordinates form
print()

mat_arr = mat.toarray()
print(mat_arr)  # matrix form

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 5 stored elements and shape (4, 5)>
  Coords	Values
  (1, 0)	9
  (0, 1)	2
  (2, 2)	7
  (0, 3)	4
  (3, 3)	3

[[0 2 0 4 0]
 [9 0 0 0 0]
 [0 0 7 0 0]
 [0 0 0 3 0]]


In [ ]:
# implementing coo_matrix (coordinate format) [faster]

import numpy as np
from scipy.sparse import coo_matrix

data = np.array([2,4,7,3,9])
row = np.array([0,0,2,3,1])
col = np.array([1,3,2,3,0])

mat = coo_matrix((data,(row,col)),shape=(4,5))
print(mat)  # coordinates form
print()

mat_arr = mat.toarray()
print(mat_arr)  # matrix form

<COOrdinate sparse matrix of dtype 'int64'
	with 5 stored elements and shape (4, 5)>
  Coords	Values
  (0, 1)	2
  (0, 3)	4
  (2, 2)	7
  (3, 3)	3
  (1, 0)	9

[[0 2 0 4 0]
 [9 0 0 0 0]
 [0 0 7 0 0]
 [0 0 0 3 0]]


In [ ]:
# implementing lil_matrix (list of lists matrix)

import numpy as np
from scipy.sparse import lil_matrix

data = np.array([2,4,7,3,9])
row = np.array([0,0,2,3,1])
col = np.array([1,3,2,3,0])

mat = lil_matrix((4,5)).astype(np.int64)  # creates a matrix with all entries as 0

for i in range(len(row)):
  mat[row[i],col[i]] = data[i]

print(mat.toarray())

[[0 2 0 4 0]
 [9 0 0 0 0]
 [0 0 7 0 0]
 [0 0 0 3 0]]


In [ ]:
import numpy as np
from scipy.sparse import dok_matrix

data = np.array([2,4,7,3,9])
row = np.array([0,0,2,3,1])
col = np.array([1,3,2,3,0])

mat = dok_matrix((4,5)).astype(np.int64)  # initializes a matrix with all entries as 0

for i in range(len(row)):
  mat[row[i],col[i]] = data[i]

print(mat.toarray())

[[0 2 0 4 0]
 [9 0 0 0 0]
 [0 0 7 0 0]
 [0 0 0 3 0]]


In [ ]:
import numpy as np
from scipy.sparse import dia_matrix

data = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
mat = dia_matrix(data)  # coordinate form
print(mat)
print()

offsets = np.array([0,1,-1])
mat1 = dia_matrix((data,offsets),shape=(5,5))  # matrix form
print(mat1.toarray())

# offsets
# 0 = main diagonal
# 1 = sub diagonal (below main diagonal)
# -1 = super diagonal (above main diagonal)

<DIAgonal sparse matrix of dtype 'int64'
	with 15 stored elements (7 diagonals) and shape (3, 5)>
  Coords	Values
  (2, 0)	11
  (1, 0)	6
  (2, 1)	12
  (0, 0)	1
  (1, 1)	7
  (2, 2)	13
  (0, 1)	2
  (1, 2)	8
  (2, 3)	14
  (0, 2)	3
  (1, 3)	9
  (2, 4)	15
  (0, 3)	4
  (1, 4)	10
  (0, 4)	5

[[ 1  7  0  0  0]
 [11  2  8  0  0]
 [ 0 12  3  9  0]
 [ 0  0 13  4 10]
 [ 0  0  0 14  5]]
